title: Vatsal's Research Homepage
description: Control and  Optimization Researcher
baseurl: "" # leave blank for user/organization site
url: "https://vatsal-iitb.github.io"
remote_theme: "mmistakes/minimal-mistakes@4.26.1"
plugins:
  - jekyll-include-cache

# Optional, but recommended:
minimal_mistakes_skin: "default" # or "air", "aqua", "contrast", "dark", etc.
locale: "en-US"
