title: Vatsal's Research Homepage
description: Control and Optimization Researcher
baseurl: "" # leave blank for user/organization site
url: "https://vatsal-iitb.github.io"
remote_theme: "mmistakes/minimal-mistakes@4.26.1"
plugins:
  - jekyll-include-cache

# Appearance
minimal_mistakes_skin: "default"
locale: "en-US"

# Pages collection for custom pages
collections:
  pages:
    output: true
    permalink: /:title/
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
